stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data
  
  prepare_base_mdel:
    cmd: src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOPS
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: src/cnnClassifier/pipeline/stage_03_model_trainer.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATIOIN
    outs:
      - artifacts/training/model.h5
  evaluations:
    cmd: src/cnnClassifier/pipeline/stage_04_evaluation_manager.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_evaluation_manager.py
      - config/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/training/model.h5
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
